#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="liongym")]
	public partial class dblionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertADMINISTRACION(ADMINISTRACION instance);
    partial void UpdateADMINISTRACION(ADMINISTRACION instance);
    partial void DeleteADMINISTRACION(ADMINISTRACION instance);
    partial void InsertPAGOS(PAGOS instance);
    partial void UpdatePAGOS(PAGOS instance);
    partial void DeletePAGOS(PAGOS instance);
    partial void InsertASISTENCIA(ASISTENCIA instance);
    partial void UpdateASISTENCIA(ASISTENCIA instance);
    partial void DeleteASISTENCIA(ASISTENCIA instance);
    partial void InsertCLIENTES(CLIENTES instance);
    partial void UpdateCLIENTES(CLIENTES instance);
    partial void DeleteCLIENTES(CLIENTES instance);
    partial void InsertCONTROL_PESO(CONTROL_PESO instance);
    partial void UpdateCONTROL_PESO(CONTROL_PESO instance);
    partial void DeleteCONTROL_PESO(CONTROL_PESO instance);
    partial void InsertMEMBRESIA(MEMBRESIA instance);
    partial void UpdateMEMBRESIA(MEMBRESIA instance);
    partial void DeleteMEMBRESIA(MEMBRESIA instance);
    #endregion
		
		public dblionDataContext() : 
				base(global::LionApp.Properties.Settings.Default.liongymConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dblionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMINISTRACION> ADMINISTRACION
		{
			get
			{
				return this.GetTable<ADMINISTRACION>();
			}
		}
		
		public System.Data.Linq.Table<PAGOS> PAGOS
		{
			get
			{
				return this.GetTable<PAGOS>();
			}
		}
		
		public System.Data.Linq.Table<ASISTENCIA> ASISTENCIA
		{
			get
			{
				return this.GetTable<ASISTENCIA>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTES> CLIENTES
		{
			get
			{
				return this.GetTable<CLIENTES>();
			}
		}
		
		public System.Data.Linq.Table<CONTROL_PESO> CONTROL_PESO
		{
			get
			{
				return this.GetTable<CONTROL_PESO>();
			}
		}
		
		public System.Data.Linq.Table<MEMBRESIA> MEMBRESIA
		{
			get
			{
				return this.GetTable<MEMBRESIA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMINISTRACION")]
	public partial class ADMINISTRACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ADMIN;
		
		private string _NOMBRE_ADMIN;
		
		private string _CLAVE_ADMIN;
		
		private EntitySet<PAGOS> _PAGOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ADMINChanging(int value);
    partial void OnID_ADMINChanged();
    partial void OnNOMBRE_ADMINChanging(string value);
    partial void OnNOMBRE_ADMINChanged();
    partial void OnCLAVE_ADMINChanging(string value);
    partial void OnCLAVE_ADMINChanged();
    #endregion
		
		public ADMINISTRACION()
		{
			this._PAGOS = new EntitySet<PAGOS>(new Action<PAGOS>(this.attach_PAGOS), new Action<PAGOS>(this.detach_PAGOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADMIN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ADMIN
		{
			get
			{
				return this._ID_ADMIN;
			}
			set
			{
				if ((this._ID_ADMIN != value))
				{
					this.OnID_ADMINChanging(value);
					this.SendPropertyChanging();
					this._ID_ADMIN = value;
					this.SendPropertyChanged("ID_ADMIN");
					this.OnID_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_ADMIN", DbType="VarChar(250)")]
		public string NOMBRE_ADMIN
		{
			get
			{
				return this._NOMBRE_ADMIN;
			}
			set
			{
				if ((this._NOMBRE_ADMIN != value))
				{
					this.OnNOMBRE_ADMINChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_ADMIN = value;
					this.SendPropertyChanged("NOMBRE_ADMIN");
					this.OnNOMBRE_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE_ADMIN", DbType="VarChar(100)")]
		public string CLAVE_ADMIN
		{
			get
			{
				return this._CLAVE_ADMIN;
			}
			set
			{
				if ((this._CLAVE_ADMIN != value))
				{
					this.OnCLAVE_ADMINChanging(value);
					this.SendPropertyChanging();
					this._CLAVE_ADMIN = value;
					this.SendPropertyChanged("CLAVE_ADMIN");
					this.OnCLAVE_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMINISTRACION_PAGOS", Storage="_PAGOS", ThisKey="ID_ADMIN", OtherKey="ID_ADMIN")]
		public EntitySet<PAGOS> PAGOS
		{
			get
			{
				return this._PAGOS;
			}
			set
			{
				this._PAGOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PAGOS(PAGOS entity)
		{
			this.SendPropertyChanging();
			entity.ADMINISTRACION = this;
		}
		
		private void detach_PAGOS(PAGOS entity)
		{
			this.SendPropertyChanging();
			entity.ADMINISTRACION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAGOS")]
	public partial class PAGOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_PAGO;
		
		private System.Nullable<int> _ID_ADMIN;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<int> _ID_MEM;
		
		private System.Nullable<decimal> _VALOR_PAGO;
		
		private System.Nullable<System.DateTime> _FECHA_PAGO;
		
		private System.Nullable<char> _TIPO_PAGO;
		
		private EntityRef<ADMINISTRACION> _ADMINISTRACION;
		
		private EntityRef<CLIENTES> _CLIENTES;
		
		private EntityRef<MEMBRESIA> _MEMBRESIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PAGOChanging(long value);
    partial void OnID_PAGOChanged();
    partial void OnID_ADMINChanging(System.Nullable<int> value);
    partial void OnID_ADMINChanged();
    partial void OnCEDULA_CLIENTEChanging(string value);
    partial void OnCEDULA_CLIENTEChanged();
    partial void OnID_MEMChanging(System.Nullable<int> value);
    partial void OnID_MEMChanged();
    partial void OnVALOR_PAGOChanging(System.Nullable<decimal> value);
    partial void OnVALOR_PAGOChanged();
    partial void OnFECHA_PAGOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_PAGOChanged();
    partial void OnTIPO_PAGOChanging(System.Nullable<char> value);
    partial void OnTIPO_PAGOChanged();
    #endregion
		
		public PAGOS()
		{
			this._ADMINISTRACION = default(EntityRef<ADMINISTRACION>);
			this._CLIENTES = default(EntityRef<CLIENTES>);
			this._MEMBRESIA = default(EntityRef<MEMBRESIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAGO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID_PAGO
		{
			get
			{
				return this._ID_PAGO;
			}
			set
			{
				if ((this._ID_PAGO != value))
				{
					this.OnID_PAGOChanging(value);
					this.SendPropertyChanging();
					this._ID_PAGO = value;
					this.SendPropertyChanged("ID_PAGO");
					this.OnID_PAGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADMIN", DbType="Int")]
		public System.Nullable<int> ID_ADMIN
		{
			get
			{
				return this._ID_ADMIN;
			}
			set
			{
				if ((this._ID_ADMIN != value))
				{
					if (this._ADMINISTRACION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ADMINChanging(value);
					this.SendPropertyChanging();
					this._ID_ADMIN = value;
					this.SendPropertyChanged("ID_ADMIN");
					this.OnID_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(50)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					if (this._CLIENTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCEDULA_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CEDULA_CLIENTE = value;
					this.SendPropertyChanged("CEDULA_CLIENTE");
					this.OnCEDULA_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MEM", DbType="Int")]
		public System.Nullable<int> ID_MEM
		{
			get
			{
				return this._ID_MEM;
			}
			set
			{
				if ((this._ID_MEM != value))
				{
					if (this._MEMBRESIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MEMChanging(value);
					this.SendPropertyChanging();
					this._ID_MEM = value;
					this.SendPropertyChanged("ID_MEM");
					this.OnID_MEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PAGO", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> VALOR_PAGO
		{
			get
			{
				return this._VALOR_PAGO;
			}
			set
			{
				if ((this._VALOR_PAGO != value))
				{
					this.OnVALOR_PAGOChanging(value);
					this.SendPropertyChanging();
					this._VALOR_PAGO = value;
					this.SendPropertyChanged("VALOR_PAGO");
					this.OnVALOR_PAGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PAGO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PAGO
		{
			get
			{
				return this._FECHA_PAGO;
			}
			set
			{
				if ((this._FECHA_PAGO != value))
				{
					this.OnFECHA_PAGOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_PAGO = value;
					this.SendPropertyChanged("FECHA_PAGO");
					this.OnFECHA_PAGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_PAGO", DbType="Char(1)")]
		public System.Nullable<char> TIPO_PAGO
		{
			get
			{
				return this._TIPO_PAGO;
			}
			set
			{
				if ((this._TIPO_PAGO != value))
				{
					this.OnTIPO_PAGOChanging(value);
					this.SendPropertyChanging();
					this._TIPO_PAGO = value;
					this.SendPropertyChanged("TIPO_PAGO");
					this.OnTIPO_PAGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMINISTRACION_PAGOS", Storage="_ADMINISTRACION", ThisKey="ID_ADMIN", OtherKey="ID_ADMIN", IsForeignKey=true)]
		public ADMINISTRACION ADMINISTRACION
		{
			get
			{
				return this._ADMINISTRACION.Entity;
			}
			set
			{
				ADMINISTRACION previousValue = this._ADMINISTRACION.Entity;
				if (((previousValue != value) 
							|| (this._ADMINISTRACION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADMINISTRACION.Entity = null;
						previousValue.PAGOS.Remove(this);
					}
					this._ADMINISTRACION.Entity = value;
					if ((value != null))
					{
						value.PAGOS.Add(this);
						this._ID_ADMIN = value.ID_ADMIN;
					}
					else
					{
						this._ID_ADMIN = default(Nullable<int>);
					}
					this.SendPropertyChanged("ADMINISTRACION");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_PAGOS", Storage="_CLIENTES", ThisKey="CEDULA_CLIENTE", OtherKey="CEDULA_CLIENTE", IsForeignKey=true)]
		public CLIENTES CLIENTES
		{
			get
			{
				return this._CLIENTES.Entity;
			}
			set
			{
				CLIENTES previousValue = this._CLIENTES.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTES.Entity = null;
						previousValue.PAGOS.Remove(this);
					}
					this._CLIENTES.Entity = value;
					if ((value != null))
					{
						value.PAGOS.Add(this);
						this._CEDULA_CLIENTE = value.CEDULA_CLIENTE;
					}
					else
					{
						this._CEDULA_CLIENTE = default(string);
					}
					this.SendPropertyChanged("CLIENTES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MEMBRESIA_PAGOS", Storage="_MEMBRESIA", ThisKey="ID_MEM", OtherKey="ID_MEM", IsForeignKey=true)]
		public MEMBRESIA MEMBRESIA
		{
			get
			{
				return this._MEMBRESIA.Entity;
			}
			set
			{
				MEMBRESIA previousValue = this._MEMBRESIA.Entity;
				if (((previousValue != value) 
							|| (this._MEMBRESIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MEMBRESIA.Entity = null;
						previousValue.PAGOS.Remove(this);
					}
					this._MEMBRESIA.Entity = value;
					if ((value != null))
					{
						value.PAGOS.Add(this);
						this._ID_MEM = value.ID_MEM;
					}
					else
					{
						this._ID_MEM = default(Nullable<int>);
					}
					this.SendPropertyChanged("MEMBRESIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ASISTENCIA")]
	public partial class ASISTENCIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_ASIS;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<System.DateTime> _FECHA_ASIS;
		
		private EntityRef<CLIENTES> _CLIENTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ASISChanging(long value);
    partial void OnID_ASISChanged();
    partial void OnCEDULA_CLIENTEChanging(string value);
    partial void OnCEDULA_CLIENTEChanged();
    partial void OnFECHA_ASISChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_ASISChanged();
    #endregion
		
		public ASISTENCIA()
		{
			this._CLIENTES = default(EntityRef<CLIENTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ASIS", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID_ASIS
		{
			get
			{
				return this._ID_ASIS;
			}
			set
			{
				if ((this._ID_ASIS != value))
				{
					this.OnID_ASISChanging(value);
					this.SendPropertyChanging();
					this._ID_ASIS = value;
					this.SendPropertyChanged("ID_ASIS");
					this.OnID_ASISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(50)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					if (this._CLIENTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCEDULA_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CEDULA_CLIENTE = value;
					this.SendPropertyChanged("CEDULA_CLIENTE");
					this.OnCEDULA_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ASIS", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ASIS
		{
			get
			{
				return this._FECHA_ASIS;
			}
			set
			{
				if ((this._FECHA_ASIS != value))
				{
					this.OnFECHA_ASISChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ASIS = value;
					this.SendPropertyChanged("FECHA_ASIS");
					this.OnFECHA_ASISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_ASISTENCIA", Storage="_CLIENTES", ThisKey="CEDULA_CLIENTE", OtherKey="CEDULA_CLIENTE", IsForeignKey=true)]
		public CLIENTES CLIENTES
		{
			get
			{
				return this._CLIENTES.Entity;
			}
			set
			{
				CLIENTES previousValue = this._CLIENTES.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTES.Entity = null;
						previousValue.ASISTENCIA.Remove(this);
					}
					this._CLIENTES.Entity = value;
					if ((value != null))
					{
						value.ASISTENCIA.Add(this);
						this._CEDULA_CLIENTE = value.CEDULA_CLIENTE;
					}
					else
					{
						this._CEDULA_CLIENTE = default(string);
					}
					this.SendPropertyChanged("CLIENTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTES")]
	public partial class CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID_CLIENTE;
		
		private string _NOMBRE_CLIENTE;
		
		private string _APELLIDO_CLIENTE;
		
		private string _CORREO_CLIENTE;
		
		private string _FOTO_CLIENTE;
		
		private System.Nullable<System.DateTime> _FECHA_NACIMIENTO_CLIENTE;
		
		private string _TELEFONO_CLIENTE;
		
		private string _CEDULA_CLIENTE;
		
		private EntitySet<PAGOS> _PAGOS;
		
		private EntitySet<ASISTENCIA> _ASISTENCIA;
		
		private EntitySet<CONTROL_PESO> _CONTROL_PESO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLIENTEChanging(System.Nullable<int> value);
    partial void OnID_CLIENTEChanged();
    partial void OnNOMBRE_CLIENTEChanging(string value);
    partial void OnNOMBRE_CLIENTEChanged();
    partial void OnAPELLIDO_CLIENTEChanging(string value);
    partial void OnAPELLIDO_CLIENTEChanged();
    partial void OnCORREO_CLIENTEChanging(string value);
    partial void OnCORREO_CLIENTEChanged();
    partial void OnFOTO_CLIENTEChanging(string value);
    partial void OnFOTO_CLIENTEChanged();
    partial void OnFECHA_NACIMIENTO_CLIENTEChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_NACIMIENTO_CLIENTEChanged();
    partial void OnTELEFONO_CLIENTEChanging(string value);
    partial void OnTELEFONO_CLIENTEChanged();
    partial void OnCEDULA_CLIENTEChanging(string value);
    partial void OnCEDULA_CLIENTEChanged();
    #endregion
		
		public CLIENTES()
		{
			this._PAGOS = new EntitySet<PAGOS>(new Action<PAGOS>(this.attach_PAGOS), new Action<PAGOS>(this.detach_PAGOS));
			this._ASISTENCIA = new EntitySet<ASISTENCIA>(new Action<ASISTENCIA>(this.attach_ASISTENCIA), new Action<ASISTENCIA>(this.detach_ASISTENCIA));
			this._CONTROL_PESO = new EntitySet<CONTROL_PESO>(new Action<CONTROL_PESO>(this.attach_CONTROL_PESO), new Action<CONTROL_PESO>(this.detach_CONTROL_PESO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", DbType="Int")]
		public System.Nullable<int> ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CLIENTE", DbType="VarChar(150)")]
		public string NOMBRE_CLIENTE
		{
			get
			{
				return this._NOMBRE_CLIENTE;
			}
			set
			{
				if ((this._NOMBRE_CLIENTE != value))
				{
					this.OnNOMBRE_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_CLIENTE = value;
					this.SendPropertyChanged("NOMBRE_CLIENTE");
					this.OnNOMBRE_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_CLIENTE", DbType="VarChar(150)")]
		public string APELLIDO_CLIENTE
		{
			get
			{
				return this._APELLIDO_CLIENTE;
			}
			set
			{
				if ((this._APELLIDO_CLIENTE != value))
				{
					this.OnAPELLIDO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO_CLIENTE = value;
					this.SendPropertyChanged("APELLIDO_CLIENTE");
					this.OnAPELLIDO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_CLIENTE", DbType="VarChar(255)")]
		public string CORREO_CLIENTE
		{
			get
			{
				return this._CORREO_CLIENTE;
			}
			set
			{
				if ((this._CORREO_CLIENTE != value))
				{
					this.OnCORREO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CORREO_CLIENTE = value;
					this.SendPropertyChanged("CORREO_CLIENTE");
					this.OnCORREO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_CLIENTE", DbType="VarChar(100)")]
		public string FOTO_CLIENTE
		{
			get
			{
				return this._FOTO_CLIENTE;
			}
			set
			{
				if ((this._FOTO_CLIENTE != value))
				{
					this.OnFOTO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._FOTO_CLIENTE = value;
					this.SendPropertyChanged("FOTO_CLIENTE");
					this.OnFOTO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO_CLIENTE", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_NACIMIENTO_CLIENTE
		{
			get
			{
				return this._FECHA_NACIMIENTO_CLIENTE;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO_CLIENTE != value))
				{
					this.OnFECHA_NACIMIENTO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._FECHA_NACIMIENTO_CLIENTE = value;
					this.SendPropertyChanged("FECHA_NACIMIENTO_CLIENTE");
					this.OnFECHA_NACIMIENTO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO_CLIENTE", DbType="VarChar(11)")]
		public string TELEFONO_CLIENTE
		{
			get
			{
				return this._TELEFONO_CLIENTE;
			}
			set
			{
				if ((this._TELEFONO_CLIENTE != value))
				{
					this.OnTELEFONO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO_CLIENTE = value;
					this.SendPropertyChanged("TELEFONO_CLIENTE");
					this.OnTELEFONO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this.OnCEDULA_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CEDULA_CLIENTE = value;
					this.SendPropertyChanged("CEDULA_CLIENTE");
					this.OnCEDULA_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_PAGOS", Storage="_PAGOS", ThisKey="CEDULA_CLIENTE", OtherKey="CEDULA_CLIENTE")]
		public EntitySet<PAGOS> PAGOS
		{
			get
			{
				return this._PAGOS;
			}
			set
			{
				this._PAGOS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_ASISTENCIA", Storage="_ASISTENCIA", ThisKey="CEDULA_CLIENTE", OtherKey="CEDULA_CLIENTE")]
		public EntitySet<ASISTENCIA> ASISTENCIA
		{
			get
			{
				return this._ASISTENCIA;
			}
			set
			{
				this._ASISTENCIA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_CONTROL_PESO", Storage="_CONTROL_PESO", ThisKey="CEDULA_CLIENTE", OtherKey="CEDULA_CLIENTE")]
		public EntitySet<CONTROL_PESO> CONTROL_PESO
		{
			get
			{
				return this._CONTROL_PESO;
			}
			set
			{
				this._CONTROL_PESO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PAGOS(PAGOS entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = this;
		}
		
		private void detach_PAGOS(PAGOS entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = null;
		}
		
		private void attach_ASISTENCIA(ASISTENCIA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = this;
		}
		
		private void detach_ASISTENCIA(ASISTENCIA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = null;
		}
		
		private void attach_CONTROL_PESO(CONTROL_PESO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = this;
		}
		
		private void detach_CONTROL_PESO(CONTROL_PESO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONTROL_PESO")]
	public partial class CONTROL_PESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_PESO;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<System.DateTime> _FECHA_PESO;
		
		private System.Nullable<decimal> _VALOR_PESO;
		
		private EntityRef<CLIENTES> _CLIENTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PESOChanging(long value);
    partial void OnID_PESOChanged();
    partial void OnCEDULA_CLIENTEChanging(string value);
    partial void OnCEDULA_CLIENTEChanged();
    partial void OnFECHA_PESOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_PESOChanged();
    partial void OnVALOR_PESOChanging(System.Nullable<decimal> value);
    partial void OnVALOR_PESOChanged();
    #endregion
		
		public CONTROL_PESO()
		{
			this._CLIENTES = default(EntityRef<CLIENTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PESO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID_PESO
		{
			get
			{
				return this._ID_PESO;
			}
			set
			{
				if ((this._ID_PESO != value))
				{
					this.OnID_PESOChanging(value);
					this.SendPropertyChanging();
					this._ID_PESO = value;
					this.SendPropertyChanged("ID_PESO");
					this.OnID_PESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(50)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					if (this._CLIENTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCEDULA_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CEDULA_CLIENTE = value;
					this.SendPropertyChanged("CEDULA_CLIENTE");
					this.OnCEDULA_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PESO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PESO
		{
			get
			{
				return this._FECHA_PESO;
			}
			set
			{
				if ((this._FECHA_PESO != value))
				{
					this.OnFECHA_PESOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_PESO = value;
					this.SendPropertyChanged("FECHA_PESO");
					this.OnFECHA_PESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PESO", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> VALOR_PESO
		{
			get
			{
				return this._VALOR_PESO;
			}
			set
			{
				if ((this._VALOR_PESO != value))
				{
					this.OnVALOR_PESOChanging(value);
					this.SendPropertyChanging();
					this._VALOR_PESO = value;
					this.SendPropertyChanged("VALOR_PESO");
					this.OnVALOR_PESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_CONTROL_PESO", Storage="_CLIENTES", ThisKey="CEDULA_CLIENTE", OtherKey="CEDULA_CLIENTE", IsForeignKey=true)]
		public CLIENTES CLIENTES
		{
			get
			{
				return this._CLIENTES.Entity;
			}
			set
			{
				CLIENTES previousValue = this._CLIENTES.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTES.Entity = null;
						previousValue.CONTROL_PESO.Remove(this);
					}
					this._CLIENTES.Entity = value;
					if ((value != null))
					{
						value.CONTROL_PESO.Add(this);
						this._CEDULA_CLIENTE = value.CEDULA_CLIENTE;
					}
					else
					{
						this._CEDULA_CLIENTE = default(string);
					}
					this.SendPropertyChanged("CLIENTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MEMBRESIA")]
	public partial class MEMBRESIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MEM;
		
		private string _NOMBRE_MEM;
		
		private string _DESCRIP_MEM;
		
		private System.Nullable<decimal> _VALOR_MEM;
		
		private System.Nullable<int> _DIAS_MEM;
		
		private EntitySet<PAGOS> _PAGOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MEMChanging(int value);
    partial void OnID_MEMChanged();
    partial void OnNOMBRE_MEMChanging(string value);
    partial void OnNOMBRE_MEMChanged();
    partial void OnDESCRIP_MEMChanging(string value);
    partial void OnDESCRIP_MEMChanged();
    partial void OnVALOR_MEMChanging(System.Nullable<decimal> value);
    partial void OnVALOR_MEMChanged();
    partial void OnDIAS_MEMChanging(System.Nullable<int> value);
    partial void OnDIAS_MEMChanged();
    #endregion
		
		public MEMBRESIA()
		{
			this._PAGOS = new EntitySet<PAGOS>(new Action<PAGOS>(this.attach_PAGOS), new Action<PAGOS>(this.detach_PAGOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MEM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_MEM
		{
			get
			{
				return this._ID_MEM;
			}
			set
			{
				if ((this._ID_MEM != value))
				{
					this.OnID_MEMChanging(value);
					this.SendPropertyChanging();
					this._ID_MEM = value;
					this.SendPropertyChanged("ID_MEM");
					this.OnID_MEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MEM", DbType="VarChar(20)")]
		public string NOMBRE_MEM
		{
			get
			{
				return this._NOMBRE_MEM;
			}
			set
			{
				if ((this._NOMBRE_MEM != value))
				{
					this.OnNOMBRE_MEMChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_MEM = value;
					this.SendPropertyChanged("NOMBRE_MEM");
					this.OnNOMBRE_MEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_MEM", DbType="VarChar(200)")]
		public string DESCRIP_MEM
		{
			get
			{
				return this._DESCRIP_MEM;
			}
			set
			{
				if ((this._DESCRIP_MEM != value))
				{
					this.OnDESCRIP_MEMChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP_MEM = value;
					this.SendPropertyChanged("DESCRIP_MEM");
					this.OnDESCRIP_MEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_MEM", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> VALOR_MEM
		{
			get
			{
				return this._VALOR_MEM;
			}
			set
			{
				if ((this._VALOR_MEM != value))
				{
					this.OnVALOR_MEMChanging(value);
					this.SendPropertyChanging();
					this._VALOR_MEM = value;
					this.SendPropertyChanged("VALOR_MEM");
					this.OnVALOR_MEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIAS_MEM", DbType="Int")]
		public System.Nullable<int> DIAS_MEM
		{
			get
			{
				return this._DIAS_MEM;
			}
			set
			{
				if ((this._DIAS_MEM != value))
				{
					this.OnDIAS_MEMChanging(value);
					this.SendPropertyChanging();
					this._DIAS_MEM = value;
					this.SendPropertyChanged("DIAS_MEM");
					this.OnDIAS_MEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MEMBRESIA_PAGOS", Storage="_PAGOS", ThisKey="ID_MEM", OtherKey="ID_MEM")]
		public EntitySet<PAGOS> PAGOS
		{
			get
			{
				return this._PAGOS;
			}
			set
			{
				this._PAGOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PAGOS(PAGOS entity)
		{
			this.SendPropertyChanging();
			entity.MEMBRESIA = this;
		}
		
		private void detach_PAGOS(PAGOS entity)
		{
			this.SendPropertyChanging();
			entity.MEMBRESIA = null;
		}
	}
}
#pragma warning restore 1591
